---
- name: Run test tasks
  ansible.builtin.import_tasks: test.yaml
  tags: always

# Variable configuration.
- name: Setup variables
  ansible.builtin.import_tasks: setup-vars.yaml
  tags: always

- name: Import uninstallation tasks
  ansible.builtin.import_tasks: uninstall.yaml
  tags: uninstall
  when: postgresql_uninstall_1 | bool and postgresql_uninstall_2 | bool

- name: Import auto tunning tasks
  ansible.builtin.import_tasks: autotune.yaml
  when: postgresql_autotune | bool
  tags:
    - auto-tune
    - autotune

- name: Import installation tasks
  ansible.builtin.import_tasks: install.yaml
  tags: install

- name: Import initialization tasks
  ansible.builtin.import_tasks: initialize.yaml
  tags:
    - init
    - initialize
    - initialise

- name: Import configuration tasks
  ansible.builtin.import_tasks: configure.yaml
  tags:
    - config
    - configure
    - configuration

- name: Import replication tasks
  ansible.builtin.import_tasks: replication.yaml
  when: postgresql_replication
  tags:
    - repli
    - replication

- name: Import backup tasks
  ansible.builtin.import_tasks: backup.yaml
  tags: backup

# Configure PostgreSQL.
- name: Import user management tasks
  ansible.builtin.import_tasks: users.yaml
  tags:
    - user
    - users

- name: Import databases tasks
  ansible.builtin.import_tasks: databases.yaml
  tags:
    - db
    - database
    - databases

- name: Import extensions tasks
  ansible.builtin.import_tasks: extensions.yaml
  tags:
    - ext
    - extension
    - extensions
