---

- name: "Starting postgresql server if not started ... (previous fails)"
  ansible.builtin.service:
    name: postgresql
    state: started

- name: Check replication status on slave ... (psql cmd)
  ansible.builtin.shell: >
    set -o pipefail ;
    {{ postgresql_bin_path }}/psql -x -c 'select * from pg_stat_wal_receiver;' | grep status | awk '{print $3}'
  args:
    executable: /bin/bash
  register: postgresql_replication_status
  changed_when: false
  become_user: "{{ postgresql_user }}"
  when: postgresql_replication_role == "slave"

- name: Check replication slot on master ... (psql cmd)
  ansible.builtin.shell: >
    set -o pipefail ;
    {{ postgresql_bin_path }}/psql -x -c 'select * from pg_replication_slots;' | grep standby1_slot | awk '{print $3}'
  args:
    executable: /bin/bash
  register: postgresql_replication_slot_check
  changed_when: false
  become_user: "{{ postgresql_user }}"
  when: postgresql_replication_role == "master"

- name: Check replication status on slave ... (recovery.conf)
  ansible.builtin.stat:
    path: "{{ postgresql_data_dir }}/recovery.conf"
  register: recovery_conf
  when: postgresql_replication_role == "slave"

- name: Ensure replication user is present
  community.postgresql.postgresql_user:
    name: "{{ postgresql_replication_user }}"
    password: "{{ postgresql_replication_password }}"
    encrypted: true
    expires: infinity
    role_attr_flags: REPLICATION
    state: present
  # no_log: true
  become: true
  become_user: "{{ postgresql_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: Debug postgresql_replication_status output
  ansible.builtin.debug:
    var: postgresql_replication_status.stdout

- name: Debug postgresql_replication_slot_check output
  ansible.builtin.debug:
    var: postgresql_replication_slot_check.stdout

- name: "Stopping postgresql server ..."
  ansible.builtin.service:
    name: postgresql
    state: stopped
  when:
    - postgresql_replication_role == "slave"
    - postgresql_replication_status.stdout is undefined or postgresql_replication_status.stdout | length == 0
    - not recovery_conf.stat.exists

- name: Removing all server datas
  ansible.builtin.file:
    dest: "{{ postgresql_data_dir }}"
    state: absent
  when:
    - postgresql_replication_role == "slave"
    - postgresql_replication_status.stdout is undefined or postgresql_replication_status.stdout | length == 0
    - not recovery_conf.stat.exists

- name: "Deploy .pgpass file for {{ postgresql_user }}"
  ansible.builtin.template:
    src: pgpass.j2
    dest: "~{{ postgresql_user }}/.pgpass"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    mode: 0400
  when:
    - postgresql_replication_role == "slave"
    - postgresql_replication_status.stdout is undefined or postgresql_replication_status.stdout | length == 0
    - not recovery_conf.stat.exists

- name: "Create datas dir {{ postgresql_data_dir }}"
  ansible.builtin.file:
    path: "{{ postgresql_data_dir }}"
    state: directory
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: "{{ postgresql_data_dir_perm }}"
  when:
    - postgresql_replication_role == "slave"
    - postgresql_replication_status.stdout is undefined or postgresql_replication_status.stdout | length == 0
    - not recovery_conf.stat.exists

- name: "Copy datas from master"
  ansible.builtin.command: >
    {{ postgresql_bin_path }}/pg_basebackup -c fast
    -X stream -h {{ postgresql_replication_master }}
    -U {{ postgresql_replication_user }} -D {{ postgresql_data_dir }}
  become_user: "{{ postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true
  when:
    - postgresql_replication_role == "slave"
    - postgresql_replication_status.stdout is undefined or postgresql_replication_status.stdout | length == 0
    - not recovery_conf.stat.exists

- name: "Create replication slot"
  ansible.builtin.shell: >
    set -o pipefail ;
    cd /tmp ; {{ postgresql_bin_path }}/psql -x -c "select * from pg_create_physical_replication_slot('{{ postgresql_replication_slot }}');"
  args:
    executable: /bin/bash
  become_user: "{{ postgresql_user }}"
  when:
    - postgresql_replication_role == "master"
    - postgresql_replication_slot_check.stdout is undefined or postgresql_replication_slot_check.stdout | length == 0
    - postgresql_version >= "12"

- name: "Create standby.signal for slave"
  ansible.builtin.file:
    path: "{{ postgresql_data_dir }}/standby.signal"
    state: touch
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0640
  when:
    - postgresql_replication_role == "slave"
    - postgresql_version >= "12"


- name: "Configure recovery.conf if not exists"
  ansible.builtin.template:
    src: recovery.conf.j2
    dest: "{{ postgresql_data_dir }}/recovery.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0640
  when:
    - postgresql_replication_role == "slave"
    - not recovery_conf.stat.exists
    - postgresql_version < "12"

- name: "Configure postgresql.conf for replication"
  ansible.builtin.template:
    src: replication.conf.j2
    dest: "{{ postgresql_config_path }}/conf.d/replication.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0640
  when:
    - postgresql_replication_role == "slave"
    - postgresql_version >= "12"


- name: "Starting postgresql server ..."
  ansible.builtin.service:
    name: postgresql
    state: started
  when:
    - postgresql_replication_role == "slave"
    - postgresql_replication_status.stdout is undefined or postgresql_replication_status.stdout | length == 0
    - not recovery_conf.stat.exists
