---
# - name: Show variables
#   ansible.builtin.debug:
#     var: v
#   vars:
#     v:
#       ansible_distribution: "{{ ansible_distribution }}"
#       ansible_os_family: "{{ ansible_os_family }}"
#       ansible_distribution_version: "{{ ansible_distribution_version }}"
#       ansible_distribution_major_version: "{{ ansible_distribution_major_version }}"
#       ansible_distribution_release: "{{ ansible_distribution_release }}"
- name: users.yaml
  ansible.builtin.include_tasks: tasks/users.yaml

- name: End play
  ansible.builtin.meta: end_play
  tags: always
