---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars:
    postgres_users_no_log: false
    postgresql_databases:
      - name: example
        encoding: UTF-8
        lc_collate: en_US.UTF-8
        lc_ctype: en_US.UTF-8
        conn_limit: 100
        template: template0
      - name: nreslou
      - name: toto
        state: absent

    postgresql_extensions:
      - name: pg_stat_statements
        db: nreslou

    postgresql_users:
      - name: nreslou
      - name: group1
        role_attr_flags: NOLOGIN
      - name: user1
        db: nreslou
      - name: jdoe
        password: s3cur3
        db: example
        comment: this is a test user
        expires: "Jun 21 2029"

    postgresql_privs:
      - roles: group1,user1 # group1 and user1 are granted all privs on all object wihtin the public schema of the example db
        db: example
        privs: ALL
        objs: ALL_IN_SCHEMA
        type: table
        schema: public
        grant_option: true
      - roles: nreslou # grant nreslou user all privs on nreslou database by first connecting to the postgres maintenance db
        db: postgres
        type: database
        privs: ALL
        objs: nreslou
        grant_option: true
      # - roles: nreslou
      #   db: nreslou
      #   type: function
      #   objs: add(int:int)
      #   privs: ALL
      #   grant_option: true

    postgresql_memberships:
      - groups:
          - group1
        target_roles:
          - user1
        state: present
      - groups:
          - group1
        target_roles:
          - jdoe
        state: absent
      - groups: []
        target_roles:
          - nreslou
        state: exact

  pre_tasks:
    # The Fedora 30+ container images have only C.UTF-8 installed
    # - name: Set database locale if using Fedora 30+ or RedHat 8+
    #   ansible.builtin.set_fact:
    #     postgresql_databases:
    #       - name: example
    #         lc_collate: 'C.UTF-8'
    #         lc_ctype: 'C.UTF-8'
    #   when:
    #     - ( ansible_distribution == 'Fedora' and ansible_distribution_major_version >= '30') or
    #       ( ansible_os_family == 'RedHat' and ansible_distribution_major_version in ['8','9'])

    # - name: Update apt cache.
    #   ansible.builtin.apt:
    #     update_cache: true
    #     cache_valid_time: 600
    #   changed_when: false
    #   when: ansible_os_family == 'Debian'

  roles:
    - role: claranet.postgresql

  # post_tasks:
  #   - name: Ensure postgres is running.
  #     ansible.builtin.command: "{{ _postgresql_bin_path }}/pg_ctl -D {{ postgresql_data_dir }} status"
  #     changed_when: false
  #     become: true
  #     become_user: postgres
